CREATE TABLE brew_brews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    method TEXT NOT NULL,
    input TEXT NOT NULL,
    output TEXT NOT NULL,
    grind TEXT NOT NULL,
    roast_level TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
);